### ISSUE TITLE
V100 support

### ISSUE THREAD

**Issue by yuyq96** [kwai/Megatron-Kwai#1]
Hi, I am seeking memory-saving techniques such as your pipeline-parallel-aware offloading. However, I have noticed the following statement:

> Minimum requirements
> - Hardware: One node (i.e., a server) equipped with four NVIDIA A100/A800/H100/H800 80GB GPU cards.

So, I am wondering if there are any hardware limitations for supporting pipeline-parallel-aware offloading on V100 GPU cards?

**Comment by yuantailing** [comment]
Hello @yuyq96 ,

There is no limitation in theory or in code on V100 GPU cards. However, the provided Docker image is built for 'sm_80' and 'sm_90', making it incompatible with V100 out of the box. You may need to create your own environment.

**Comment by yuyq96** [comment]
OK, thanks!
